Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -67,8 +67,9 @@ jobs:
         key: ${{ secrets.SSH_KEY }}
         script: |
           echo "Killing Old Gunicorn..."
-          pkill -f gunicorn
+          pkill -f gunicorn || true  # need to OR true since pkill returns nonzero on successful murder
 
           echo "Starting New Gunicorn..."
           cd /home/deploy/dog-breed-classifier
-          nohup .venv/bin/gunicorn --config=gunicorn_config.py "app:create_app()" > gunicorn.log 2>&1 &
+          # nohup lets it work after session ends, 2>&1 redirects stderr to stdout
+          nohup .venv/bin/gunicorn --config=gunicorn_config.py "app:create_app()" > gunicorn.log 2>&1 & 
